# NN params
threshold_buy = 1.0
threshold_sell = -1.0

learning_rate = 0.01
momentum = 0.1
decay = 0.01
stoploss_enabled = false
stoploss_threshold = 0.85
hodl_threshold = 1
price_buffer_len = 100
min_predictions = 1000

# SMA Trends
SMA_long = 1000
SMA_short = 50

# BULL
BULL_RSI = 10
BULL_RSI_high = 80
BULL_RSI_low = 60

# BEAR
BEAR_RSI = 15
BEAR_RSI_high = 50
BEAR_RSI_low = 20

# BULL/BEAR is defined by the longer SMA trends
# if SHORT over LONG = BULL
# if SHORT under LONG = BEAR